### ISSUE TITLE
convert_na_to_zeroes speed improvement

### ISSUE THREAD

**Issue by regenernate** [Benjamin-Vincent-Lab/binfotron#23]
We should consider in the convert_na_to_zeroes method checking whether the incoming dataframe is disproportionately wide and if so, we should transpose the dataframe, do the conversion to zeroes, and then transpose back. 

In a test of a dataframe with 10000 columns and 24 rows where ~75% of values are NA, runtimes were:

untransposed: 176 seconds
transposed and transposed back: .05 seconds

**Comment by DanteBortone** [comment]
Fixed by adding `transpose_for_faster_processing` as an option. A downside to using this would be if you have different classes in your columns, in which case you could lose formatting or precision.  Also not sure how many columns and NA's you need before transposing is worth it, but it's there now if we need it.
